function results = simulateSimultaneousVsRotation()
% simulateSimultaneousVsRotation
%
% Tests whether independent directional noise streams contribute
% simultaneously on each trial or whether only one stream contributes
% on a given trial.
%
% The comparison is deliberately made difficult:
%
%   randomRotation:
%       One of three readouts is selected with probability 1/3.
%       p(correct) is a mixture of three one-stream logistic functions.
%
%   simultaneousMatched:
%       All three streams contribute on every trial before a single
%       logistic nonlinearity. Its coefficients are calibrated so that
%       the ordinary marginal logistic regression coefficients match
%       those produced by randomRotation.
%
% Thus, marginal beta values alone are not sufficient. The diagnostic is
% the joint trial-by-trial dependence on the three independent streams.
%
% For every simulated data set, two likelihood models are fitted:
%
%   SUM model:
%       logistic(a + b0*C0 + b120*(Cp120 + Cm120))
%
%   MIXTURE model:
%       (1/3)*logistic(a0 + g0*C0) +
%       (1/3)*logistic(a120 + g120*Cp120) +
%       (1/3)*logistic(a120 + g120*Cm120)
%
% Models are compared using held-out log likelihood. Positive cvLLR
% favors the SUM model:
%
%       cvLLR = LL_SUM - LL_MIXTURE
%
% The program also reports the 2x2x2 noise-sign outcome cube.
%
% Chance performance is 50%. Trials use change-side noise only.
%
% This is a first-pass design simulation, not a final analysis package.

rng(1);

r120List       = [0.10 0.20 0.25];
targetPerfList = [0.70 0.75];
gammaList      = [0.10 0.20 0.30];
nTrialsList    = [10000 40000];

nRep = 50;
noiseSD = 1;
topUpFraction = 0.15;

singleDirectionCoherence75 = 20;
signalAt75 = log(0.75/0.25);

% Large fixed sample for matching coherence and marginal coefficients.
nCal = 500000;
cal.C0 = noiseSD*randn(nCal,1);
cal.Cp = noiseSD*randn(nCal,1);
cal.Cm = noiseSD*randn(nCal,1);
cal.R  = randi(3,nCal,1);

generatorList = {'randomRotation','simultaneousMatched'};

row = 0;
results = table();

for iR = 1:numel(r120List)
    r120 = r120List(iR);

    for iP = 1:numel(targetPerfList)
        targetPerf = targetPerfList(iP);

        for iG = 1:numel(gammaList)
            gamma = gammaList(iG);

            % Find coherence for the random-rotation model.
            [coherence,S,predPerf,pMatch,pWrong] = ...
                findRandomCoherence(r120,targetPerf,gamma,cal, ...
                singleDirectionCoherence75,signalAt75);

            % Estimate the marginal logistic coefficients generated by
            % random rotation. These become the simultaneous model's
            % within-trial weights.
            pRandomCal = randomProbability( ...
                cal.C0,cal.Cp,cal.Cm,cal.R,S,r120,gamma);

            yCal = rand(nCal,1) < pRandomCal;
            bMarginal = glmfit([cal.C0,cal.Cp+cal.Cm], ...
                yCal,'binomial','link','logit');

            beta0Target = bMarginal(2);
            beta120Target = bMarginal(3);

            % Tune simultaneous intercept to the same mean performance.
            alphaSim = tuneSimultaneousIntercept( ...
                targetPerf,beta0Target,beta120Target,cal);

            for iN = 1:numel(nTrialsList)
                nTrials = nTrialsList(iN);

                for iGen = 1:numel(generatorList)
                    generator = generatorList{iGen};

                    perfHat = nan(nRep,1);
                    beta0Hat = nan(nRep,1);
                    beta120Hat = nan(nRep,1);
                    cvLLR = nan(nRep,1);
                    correctModel = false(nRep,1);
                    signCube = nan(nRep,8);

                    for iRep = 1:nRep
                        sim = simulateDataset(generator,nTrials, ...
                            S,r120,gamma,alphaSim, ...
                            beta0Target,beta120Target,noiseSD);

                        perfHat(iRep) = mean(sim.y);

                        b = glmfit([sim.C0,sim.Cp+sim.Cm], ...
                            sim.y,'binomial','link','logit');
                        beta0Hat(iRep) = b(2);
                        beta120Hat(iRep) = b(3);

                        % One fixed 50/50 split per repetition.
                        train = false(nTrials,1);
                        train(randperm(nTrials,round(nTrials/2))) = true;
                        test = ~train;

                        sumPar = fitSumModel( ...
                            sim.C0(train),sim.Cp(train),sim.Cm(train), ...
                            sim.y(train));

                        mixPar = fitMixtureModel( ...
                            sim.C0(train),sim.Cp(train),sim.Cm(train), ...
                            sim.y(train),S,r120,gamma);

                        pSum = sumProbability( ...
                            sim.C0(test),sim.Cp(test),sim.Cm(test),sumPar);
                        pMix = mixtureProbability( ...
                            sim.C0(test),sim.Cp(test),sim.Cm(test),mixPar);

                        llSum = bernoulliLL(sim.y(test),pSum);
                        llMix = bernoulliLL(sim.y(test),pMix);

                        cvLLR(iRep) = llSum-llMix;

                        if strcmp(generator,'simultaneousMatched')
                            correctModel(iRep) = cvLLR(iRep) > 0;
                        else
                            correctModel(iRep) = cvLLR(iRep) < 0;
                        end

                        signCube(iRep,:) = outcomeSignCube( ...
                            sim.C0,sim.Cp,sim.Cm,sim.y);
                    end

                    row = row+1;
                    results.generator{row,1} = generator;
                    results.r120(row,1) = r120;
                    results.targetPerf(row,1) = targetPerf;
                    results.gamma(row,1) = gamma;
                    results.nTrials(row,1) = nTrials;
                    results.completedTrialsEquivalent(row,1) = ...
                        nTrials/(1-topUpFraction);
                    results.coherence(row,1) = coherence;
                    results.S(row,1) = S;
                    results.predictedPerf(row,1) = predPerf;
                    results.predictedPMatch(row,1) = pMatch;
                    results.predictedPWrong(row,1) = pWrong;
                    results.targetBeta0(row,1) = beta0Target;
                    results.targetBeta120(row,1) = beta120Target;
                    results.meanPerf(row,1) = mean(perfHat);
                    results.meanBeta0(row,1) = mean(beta0Hat);
                    results.sdBeta0(row,1) = std(beta0Hat);
                    results.meanBeta120(row,1) = mean(beta120Hat);
                    results.sdBeta120(row,1) = std(beta120Hat);
                    results.meanCvLLR(row,1) = mean(cvLLR);
                    results.sdCvLLR(row,1) = std(cvLLR);
                    results.modelRecovery(row,1) = mean(correctModel);

                    for iCell = 1:8
                        results.(sprintf('signCell%d',iCell))(row,1) = ...
                            mean(signCube(:,iCell),'omitnan');
                    end
                end
            end
        end
    end
end

disp(results);
makePlots(results);

end


function [coherence,S,meanPerf,pMatch,pWrong] = ...
    findRandomCoherence(r120,targetPerf,gamma,cal,coh75,signalAt75)

perfAtC = @(c) randomMeanPerformance( ...
    c,r120,gamma,cal,coh75,signalAt75);

lo = 0;
hi = 200;

for i = 1:70
    mid = (lo+hi)/2;
    if perfAtC(mid) < targetPerf
        lo = mid;
    else
        hi = mid;
    end
end

coherence = (lo+hi)/2;
S = signalAt75*coherence/coh75;

p = randomProbability(cal.C0,cal.Cp,cal.Cm,cal.R,S,r120,gamma);
meanPerf = mean(p);
pMatch = mean(p(cal.R==1));
pWrong = mean(p(cal.R~=1));

end


function m = randomMeanPerformance(c,r120,gamma,cal,coh75,signalAt75)

S = signalAt75*c/coh75;
p = randomProbability(cal.C0,cal.Cp,cal.Cm,cal.R,S,r120,gamma);
m = mean(p);

end


function p = randomProbability(C0,Cp,Cm,R,S,r120,gamma)

eta = zeros(size(C0));
is0 = R==1;
isP = R==2;
isM = R==3;

eta(is0) = S + gamma*C0(is0);
eta(isP) = r120*S + gamma*Cp(isP);
eta(isM) = r120*S + gamma*Cm(isM);

p = logisticLocal(eta);

end


function alpha = tuneSimultaneousIntercept( ...
    targetPerf,beta0,beta120,cal)

f = @(a) mean(logisticLocal( ...
    a + beta0*cal.C0 + beta120*(cal.Cp+cal.Cm))) - targetPerf;

alpha = fzero(f,log(targetPerf/(1-targetPerf)));

end


function sim = simulateDataset(generator,nTrials,S,r120,gamma, ...
    alphaSim,beta0Sim,beta120Sim,noiseSD)

C0 = noiseSD*randn(nTrials,1);
Cp = noiseSD*randn(nTrials,1);
Cm = noiseSD*randn(nTrials,1);

switch generator
    case 'randomRotation'
        R = randi(3,nTrials,1);
        p = randomProbability(C0,Cp,Cm,R,S,r120,gamma);

    case 'simultaneousMatched'
        R = nan(nTrials,1);
        p = logisticLocal( ...
            alphaSim + beta0Sim*C0 + beta120Sim*(Cp+Cm));

    otherwise
        error('Unknown generator: %s',generator);
end

sim.C0 = C0;
sim.Cp = Cp;
sim.Cm = Cm;
sim.y = rand(nTrials,1) < p;
sim.R = R;

end


function par = fitSumModel(C0,Cp,Cm,y)

b = glmfit([C0,Cp+Cm],y,'binomial','link','logit');
par = b;

end


function p = sumProbability(C0,Cp,Cm,par)

p = logisticLocal(par(1)+par(2)*C0+par(3)*(Cp+Cm));

end


function par = fitMixtureModel(C0,Cp,Cm,y,S,r120,gamma)

% Parameters are [a0 a120 g0 g120].
start = [S,r120*S,gamma,gamma];

objective = @(x) -bernoulliLL(y, ...
    mixtureProbability(C0,Cp,Cm,x));

options = optimset('Display','off', ...
    'MaxIter',1000,'MaxFunEvals',5000, ...
    'TolX',1e-7,'TolFun',1e-7);

par = fminsearch(objective,start,options);

end


function p = mixtureProbability(C0,Cp,Cm,par)

a0 = par(1);
a120 = par(2);
g0 = par(3);
g120 = par(4);

p = ( ...
    logisticLocal(a0+g0*C0) + ...
    logisticLocal(a120+g120*Cp) + ...
    logisticLocal(a120+g120*Cm) ) / 3;

p = min(max(p,1e-9),1-1e-9);

end


function ll = bernoulliLL(y,p)

p = min(max(p,1e-9),1-1e-9);
ll = sum(y.*log(p)+(1-y).*log(1-p));

end


function cube = outcomeSignCube(C0,Cp,Cm,y)

% Cell order:
%   ---, --+, -+-, -++, +--, +-+, ++-, +++
%
% This is descriptive only. The likelihood comparison is primary.

s0 = C0 >= 0;
sp = Cp >= 0;
sm = Cm >= 0;

cube = nan(1,8);
cellIndex = 1 + 4*s0 + 2*sp + sm;

for k = 1:8
    idx = cellIndex==k;
    if any(idx)
        cube(k) = mean(y(idx));
    end
end

end


function makePlots(results)

generatorList = unique(results.generator,'stable');
r120List = unique(results.r120);
targetPerfList = unique(results.targetPerf);
gammaList = unique(results.gamma);
nTrialsToPlot = max(results.nTrials);

% Model recovery.
for iP = 1:numel(targetPerfList)
    targetPerf = targetPerfList(iP);

    figure('Color','w');
    tiledlayout(1,numel(gammaList),'TileSpacing','compact');

    for iG = 1:numel(gammaList)
        gamma = gammaList(iG);
        nexttile;
        hold on;

        for iGen = 1:numel(generatorList)
            generator = generatorList{iGen};

            idx = strcmp(results.generator,generator) & ...
                results.targetPerf==targetPerf & ...
                results.gamma==gamma & ...
                results.nTrials==nTrialsToPlot;

            sub = sortrows(results(idx,:),'r120');

            plot(sub.r120,sub.modelRecovery,'-o', ...
                'DisplayName',generator);
        end

        yline(0.5,':','chance','HandleVisibility','off');
        xlabel('r_{120}');
        ylabel('Correct model recovery');
        ylim([0 1]);
        title(sprintf('\\gamma = %.2f',gamma));
        box off;
    end

    legend('Location','best');
    sgtitle(sprintf('SUM versus MIXTURE recovery, target P = %.2f, N = %d', ...
        targetPerf,nTrialsToPlot));
end

% Held-out log-likelihood difference.
for iP = 1:numel(targetPerfList)
    targetPerf = targetPerfList(iP);

    figure('Color','w');
    tiledlayout(1,numel(gammaList),'TileSpacing','compact');

    for iG = 1:numel(gammaList)
        gamma = gammaList(iG);
        nexttile;
        hold on;

        for iGen = 1:numel(generatorList)
            generator = generatorList{iGen};

            idx = strcmp(results.generator,generator) & ...
                results.targetPerf==targetPerf & ...
                results.gamma==gamma & ...
                results.nTrials==nTrialsToPlot;

            sub = sortrows(results(idx,:),'r120');

            errorbar(sub.r120,sub.meanCvLLR,sub.sdCvLLR,'-o', ...
                'DisplayName',generator);
        end

        yline(0,':','equal held-out likelihood', ...
            'HandleVisibility','off');
        xlabel('r_{120}');
        ylabel('LL_{SUM} - LL_{MIXTURE}');
        title(sprintf('\\gamma = %.2f',gamma));
        box off;
    end

    legend('Location','best');
    sgtitle(sprintf('Held-out model evidence, target P = %.2f, N = %d', ...
        targetPerf,nTrialsToPlot));
end

% Verify marginal matching.
figure('Color','w');
hold on;

idx = results.targetPerf==0.75 & ...
    results.gamma==0.20 & ...
    results.nTrials==nTrialsToPlot;

sub = results(idx,:);

for iGen = 1:numel(generatorList)
    generator = generatorList{iGen};
    this = sub(strcmp(sub.generator,generator),:);

    plot(this.meanBeta0,this.meanBeta120,'o', ...
        'DisplayName',generator);
end

xlabel('\beta_0');
ylabel('\beta_{120 sum}');
title('Marginal coefficients after deliberate matching');
axis square;
box off;
legend('Location','best');

end


function y = logisticLocal(x)
y = 1./(1+exp(-x));
end
